#激活哪一个环境的配置文件  java -jar xxx.jar --spring.profiles.active=jar

spring:
 profiles:
  active: "dev"
 mvc:
   view:
     prefix: /static/
     suffix: .html
   static-path-pattern: /static/**
---
spring:
 profiles: dev
server:
  port: 8088
api:
  host: http://localhost:8080/api/v1.0/
---
spring:
 profiles: jar
server:
  port: 8080
api:
  host: http://192.168.254.231:8080/api/v1.0/